### ISSUE TITLE
Package request: Tox

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#1043]
Tox is a secure messaging system https://tox.im

https://wiki.tox.im/QTox#Downloads

coretox -> must be packaged as a separate library
uTox -> X11 app (depends on coretox lib with libfreetype, opus and libvpx)
qTox -> Qt app

**Comment by bougyman** [comment]
I don't see any releases on their downloads page. Should this be a -git package for all of them like archlinux has it?

**Comment by necrophcodr** [comment]
It has now been two weeks, and https://github.com/irungentoo/toxcore still has no releases (tags).
It is unlikely to happen soon as well, a few months down the road maybe.

If this package is important, then a -git package is what it'll have to be, yeah.

However, it also appears that simply downloading the statically built µTox / uTox binary should get around that whole thing, since it does not depend on any tox-related shlibs, and it also has releases.

**Comment by Gottox** [comment]
#1102 #1101

**Comment by Gottox** [comment]
#1196

**Comment by xtraeme** [comment]
There's utox, qtox and toxic right now... enough tox clients for a long while :-)
