### ISSUE TITLE
Build-style request: qmake

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1064]

**Comment by teh-jazzman** [comment]
I am not alltogether sure that adding special build styles for the various makefile generators is really neccessary. It is not so difficult to call the generator from `do_configure` or `pre_configure`. That way you can set the build style to whatever comes after the generator, like `gnu-makefile` or maybe even `gnu-configure`. This is more versatile than adding a build style for each and every generator that pops up in the future.

**Comment by logenkain** [comment]
On Wed, Apr 22, 2015 at 12:55:20AM -0700, Stefan Mühlinghaus wrote:
> I am not alltogether sure that adding special build styles for the various makefile generators is really neccessary. 
Certainly not neccessary, but abstraction is king.
>It is not so difficult to call the generator from `do_configure` or `pre_configure`. 
True, but our templates look so pretty when it ends with a checksum.
>This is more versatile than adding a build style for each and every generator that pops up in the future.
Adding build styles for every generator would be a bit much, but in this
case, it's a pretty common generator.

I'm not trying to argue for or against multiple build styles, just
noting that all your arguments are easily countered.  But...

One thing against a lot of build styles; they may become hard to
maintain.

One thing for them; with more abstration it may encourage more people to
maintain packages.

**Comment by dominikh** [comment]
You might consider sending a patch adding a qmake build-style so that we can argue based on a real example. We have build-styles for less popular things, like Go packages. And we have more packages using qmake than Go, so there's generally no reason for not having one for qmake.

Key here is, however, that the build style can be written in a clean and generic way so that it applies to most/all packages using qmake, not just those that are fine with the defaults. Optimally you could update all templates that currently invoke qmake manually. `qpdfview` and `zeal` might be two examples for custom qmake invocations.
