### ISSUE TITLE
Konsole5-17.04.3 does not upgrade to konsole-17.12.0

### ISSUE THREAD

**Issue by Chocimier** [voidlinux/void-packages#10696]
### System

* xuname:  
  Void 4.14.12_4 x86_64 GenuineIntel uptodate
* package:  
  konsole, konsole5

### Expected behavior
Konsole5 is superseded in repository by konsole since #8456, so it should also update on user system.

### Steps to reproduce the behavior
- Have konsole5 installed on your system (because you did so some time ago, or from old git revision for testing)
- xbps-install -Su

**Comment by Chocimier** [comment]
That is not what i mean, sorry for confusing.
`xbps-install konsole` in fact removed konsole5.
Is it possible to `xbps-install -Su` also removes konsole5 and install konsole?

**Comment by pullmoll** [comment]
Oh, my bad. I thought it was a letter case issue because your subject is **K**onsole5… ;-)

To automagically update konsole5 to konsole we would need to create a dummy package, perhaps `build_style=meta` with `depends=konsole`. I am not sure, if that actually works because then `konsole` replaces the package it depends on.

Perhaps we can instead create a hint in the [wiki](https://wiki.voidlinux.eu) for people who don't know how to proceed?

**Comment by pullmoll** [comment]
Hmm.. the revbump of kde-baseapps with the changed of konsole5 to konsole should have triggered this update. This of course only, if you actually installed kde-baseapps and not the separate packages only.

**Comment by Chocimier** [comment]
I'll check if such [construct](https://github.com/voidlinux/void-packages/blob/721c85988f/srcpkgs/python-ipython_genutils/template) works.
