### ISSUE TITLE
Linux4.14: changed kernel config break bootup

### ISSUE THREAD

**Issue by Piraty** [voidlinux/void-packages#10818]
### System

* lscpu:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
...
Model name:          AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G
...
```
* xuname:  
  *Void 4.14.13_2 x86_64 AuthenticAMD uptodate rFFFFFFFFFFFF*
    (this _2 is my own build, see below)
* package:
  *linux4.14 since bd1b40da939f22fecc268e07c06474e6bfbcbd97*
  (*linux4.14.12_3* , *linux4.14.12_4* ,  *linux4.14.13_1* )

### Expected behavior
boot as usual
### Actual behavior
runit won't start up, leaving only kernel /dmesg outout on the screen.
after around [6s] there is nothing more, no console etc. It just stops output.
It actually has no error ouput upon installing/reconfiguring the kernel that indicates a problem.
### Steps to reproduce the behavior
Start my system with on of the mentioned kernels.
### temporary solution
Building the current 4.14.13 template with reverted bd1b40da939f22fecc268e07c06474e6bfbcbd97 solves the issue for me, so it's probably about one of those config options.

**Comment by Gottox** [comment]
@thypon Any idea what's happening here?

**Comment by thypon** [comment]
@Piraty could you provide me with your custom sysctl custom config (/etc/sysctl.conf, /etc/sysctl.d/*) and kernel command line if any. It is possible that, if you have `panic_on_oops` enabled (not enabled by default on VoidLinux, but enableable via command line or sysctl), the newly introduced memory checks will break the boot.

IMHO The only 3 configs that can change something about your architecture, if it is an architecture specific problem, are:
```
CONFIG_SLAB_FREELIST_RANDOM=y
CONFIG_SLAB_FREELIST_HARDENED=y
CONFIG_REFCOUNT_FULL=y
```

Could you also try disabling them one by one?

Both of them are active changes in how the semantic of SLAB and REFCOUNT are handled respectively. REFCOUNT introduce some very optimized x86_64 code in order to avoid integer wrapping, that could be a problem, never reported, on AMD almost compliant x86_64 implementation.

SLAB instead shouldn't introduce any problem since we use SLUB by default in VoidLinux.

**Comment by Piraty** [comment]
thanks for reply @thypon, i found another person with this issue here: https://forum.voidlinux.eu/t/4-14-13-1-and-4-14-12-4-not-booting-properly/4348/23

I'll try pinning down the malicious options, running my fourth kernel recompilation ...

here are the requested outputs
```
cat /etc/default/grub

# ... almost the defaults ...
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 slub_debug=P page_poison=1 pcie_aspm=force"
# ...
```

```
cat /etc/sysctl.d/*

#http://mythreed.com/2017/10/26/tweaking-void-pt2/
vm.swappiness = 5
vm.vfs_cache_pressure = 50

vm.dirty_background_ratio = 25
vm.dirty_background_bytes = 0
vm.dirty_ratio = 75
vm.dirty_bytes = 0
vm.dirty_expire_centisecs = 6000
vm.dirty_writeback_centisecs = 2000

vm.nr_hugepages=128
```

**Comment by Piraty** [comment]
problem lies in one of those.
```
CONFIG_SCHED_STACK_END_CHECK=y
CONFIG_DEBUG_SG=y
```

**Comment by thypon** [comment]
Is `cat /proc/sys/kernel/panic_on_oops` reporting 0?

I think it is the first one then. Maybe it hangs the scheduler kthread on a kernel stack corruption, during boot.

**Comment by Piraty** [comment]
yes.
```
cat /proc/sys/kernel/panic_on_oops
0
```
ok i will do one more rebuild (takes a while each time ...) but how to proceed for us / me ?

**Comment by thypon** [comment]
The correct itinerary should be to identify the bug, have a working patch, apply the working patch to our kernels and try to upstream that. Unfortunately, since I cannot reproduce that bug, it is not easy for me to regression test, debug, and create a patch.

If you can at least identify the offending option we can disable it selectively, or disable with an ERRATA for some CPUs.

I think you can enable CCACHE with XBPS_CCACHE=yes in order to speed up builds.

**Comment by Piraty** [comment]
I actually do use ccache, but thanks.
thanks for support, i will report upstream and try to achieve sth there.
will report as soon as there is something new

**Comment by thypon** [comment]
```
CONFIG_SLAB_FREELIST_RANDOM=y
CONFIG_SLAB_FREELIST_HARDENED=y
CONFIG_REFCOUNT_FULL=y
```

IMHO: the active security enhancing configs, like the first three I mentioned, are not needed and could be disabled. The DEBUG and CHECK config flags instead help to catch bugs as early as possible. I won't disable them, what it is today a non-booting system could be an even worse corrupted data partition tomorrow, with these flags disabled.

**Comment by Piraty** [comment]
ok it is this one: `CONFIG_DEBUG_SG=y`
https://github.com/voidlinux/void-packages/commit/c924a1619c7fa6902d3671a253d2bf31f117dde1 does it for me.

**Comment by cr6git** [comment]
@thypon Are you okay with @Piraty 's comment? Will you fix the issue? Thanks.

**Comment by thypon** [comment]
@cr6git yep, if a DEBUG option is causing a reboot we should disable it. DEBUG_ options should not change the external behavior, if they do, they are considered buggy themselves.

**Comment by Piraty** [comment]
@cr6git do you have the same issue? that makes more than 3 confirmed affected users then.
@thypon previously you wrote you were unlikely to revert the configs, now you say you would.
How can i help debug this?

**Comment by cr6git** [comment]
@Piraty No, I'm not directly concerned. 🛌

**Comment by thypon** [comment]
I would prefer leaving it enabled but the behaviour of blocking the boot is broken, right now.

@Piraty if you can enable and get a coredump with runit-kdump would be really useful for an official bug-report.

**Comment by Piraty** [comment]
10556c5 did it. thanks
