### ISSUE TITLE
Firefox does not play sound via ALSA

### ISSUE THREAD

**Issue by jnbr** [voidlinux/void-packages#11043]
### System

* xuname:   Void 4.14.14_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFF
* package:  firefox-58.0_1

### Expected behavior
firefox should be able to play sound via ALSA

### Actual behavior
firefox does not play sound.
The problem seems to be a sandbox rule preventing a ioctl syscall.

### Steps to reproduce the behavior
Install firefox, make sure pulseaudio is not installed, try to play audio / video with audio.

I think that the firefox template should, if there is no sane workaround to make ALSA work, depend on pulseaudio.

**Comment by Vaelatern** [comment]
Upstream decision. There is a workaround, and it's googleable.

**Comment by Anachron** [comment]
Workaround being apulse?

If yes we should at least remove "ac_add_options $(vopt_enable alsa)" from the template file.

**Comment by Duncaen** [comment]
> If yes we should at least remove "ac_add_options $(vopt_enable alsa)" from the template file.

Still works if the sandbox is disabled or the level lowered, apulse wouldn't work.
Its the same problem like using alsa direct, the missing client/server design makes it hard to sandbox.

**Comment by wine** [comment]
It seems to be an upstream bug according to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1430274 (fixed in Firefox 59 ?)

In the meantime, I found and tested two workarounds:

* If you want to continue using ALSA without installing PulseAudio, you can whitelist the blocked syscall adding it to `security.sandbox.content.syscall_whitelist` in about:config (in my case `16`)
* Another way is to use PulseAudio as a simple bridge to ALSA, configuring it as described here: https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_as_a_minimal_unintrusive_dumb_pipe_to_ALSA (credits to Max-P who wrote the guide)

Maybe my sound is safe for another day...
