### ISSUE TITLE
Package request: rustfmt

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#11743]
https://github.com/rust-lang-nursery/rustfmt/releases

**Comment by fallenwizard** [comment]
`
# Template file for 'rustfmt'
pkgname=rustfmt
version=0.3.7
revision=1
hostmakedepends="rust cargo"
short_desc="A tool for formatting Rust code according to style guidelines"
maintainer="fallenwizard <fallenwiz@protonmail.com>"
license="Apache-2.0"
homepage="https://github.com/rust-lang-nursery/rustfmt"
distfiles="$homepage/archive/$version.tar.gz"
checksum=3c1fe44db14011faaa5bf70023bbec520f7cab81a4e61c4f889b5f8b3eab321b
nocross=yes

do_build() {
    cargo build --release
}

do_install() {
    vbin target/release/rustfmt
    vbin target/release/cargofmt

    vlicense LICENSE-APACHE
    vlicense LICENSE-MIT
}
`
Sadly rustfmt won't compile because it looks like the rust version in the repo is too old.

**Comment by dleeram** [comment]
You have to use versison 0.9 of the syntex branch because Void only has rust stable. [ref](https://github.com/rust-lang-nursery/rustfmt#rustfmt----)

**Comment by cr6git** [comment]
we have `rustfmt` now, we can close this.
