### ISSUE TITLE
Package request: maven

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1176]
http://maven.apache.org/

**Comment by nmeum** [comment]
It's actually kind of difficult to package maven (at least if you want to built it from source) because it will fetch a bunch of java libraries from the internet, it doesn't use the ones provided by void. I would be great to have a workaround for this. I looked at the [archlinux package](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/maven#n34) and they just ignore that issue. Other distrubutions (like gentoo for instance) only ship the binary version of maven and don't built it from source which sucks as well.
