### ISSUE TITLE
FreeCAD 0.17 tracking issue

### ISSUE THREAD

**Issue by faulesocke** [voidlinux/void-packages#12571]
Hey guys,

I'm not sure whether it's usual here to have a tracking issue for more complex changes but I make one anyway. When reading through their forums, it seems that FreeCAD 0.17 can be expected very soon. Therefore I invested a day in compiling to make sure the current git version compiles fine in void (so that when 0.17 is released it will hopefully compile fine as well).

I had to make two new packages, vtk and med which I will PR in the next hours (currently polishing and recompiling to make sure everything works). I don't expect them to get accepted immediately, especially med is still a little bit ugly.

Here are the Steps that need to be done before we can switch to the new FreeCAD version:
- [x] Package vtk #11993
- [x] Package med #12572
- [x] Check freecad package for unnecessary dependencies

**Comment by faulesocke** [comment]
Piraty already has done a vtk package: #11993

**Comment by yopito** [comment]
hello, nice !  
Disclaimer: I've packaged FreeCAD for VoidLinux, but I don't have any CAD culture ...

They were some discussion on IRC 2 weeks ago about it with @Piraty  and @karl-nilsson .  
I don't know about `med` package, but FreeCAD 0.17 is also supposed needs OpenCascade (OCCT) instead of OCE. What's your opinion about it ? 

I have some work on vtk (also @Piraty) and OCCT packaging but not yet usable by others.
I will ping here as soon I will have something usable.

**Comment by Piraty** [comment]
Yes, freecad update is expected in near future, as my info from their irc channel suggests.
For the sake of completeness: here is my [freecad-git branch](https://github.com/Piraty/void-packages/commits/freecad-git), which makes use of the mentioned vtk PR.
As far as my findings go, no other dependency than `vtk` and `libmed` were neccesary for a succesful build of most recent freecad, and the build output does not suggest anything like `occt` is expected.
I worked on `libmed` already (see my freecad-git branch), no need to package the whole med suite.

**Comment by faulesocke** [comment]
@yopito My build worked just fine without OpenCascade. Does it add any extra features to freecad?

**Comment by karl-nilsson** [comment]
@faulesocke OpenCascade is the CAD kernel FreeCAD uses, so I'd be extremely surprised if your build functioned without it installed.

iirc, the next FreeCAD release will depend on a newer version of OpenCascade than the current oce package provides

oce is working on releasing a new version, but there's no estimated release date
https://groups.google.com/d/msg/oce-dev/Y384XPe2QNM/pSoWGNzpBgAJ

upstream opencascade does not allow anonymous downloads for source releases, only from their gitweb page
https://www.opencascade.com/sites/default/files/private/occt/OCC_7.2.0_release/opencascade-7.2.0.tgz
http://git.dev.opencascade.org/gitweb/?p=occt.git;a=shortlog

**Comment by Piraty** [comment]
A bit more info:
 - In order to compile freecad with python3 and qt5 (which i think should be done), we need `pyside2` and `shiboken2`.
- Also @faulesocke, `vtk` [got merged](https://github.com/voidlinux/void-packages/pull/11993) already (to update the top post).

Also, my stance on `med` is a rather minimal one, so i only packaged `libmed` (see my [libmed on my freecad-git branch](https://github.com/Piraty/void-packages/blob/freecad-git/srcpkgs/libmed/template)).
If Void needs more from it in the future, that might be re-worked.

**Comment by Piraty** [comment]
#### Update on OCCT / OCE

> (normandc) @Piraty you heard wrong, OCCT will not be mandatory, FreeCAD will still function with either OCE or OCCT. The decision to switch back to OCCT (we had switched to OCE in 2012) was made by the few of us who package FreeCAD for Ubuntu, Windows and Mac. The reason is that OCE's development has stalled for the past 2 years, while OCCT has released new versions regularly. OCE 18 was released last year, but it's based on OCCT 6.9.0 which was its 
> May 2015!
> while FreeCAD based on OCE 18.3 will definitely work, it will not benefit from the many bug fixes that OCCT 7.x provides. We're aiming for official FreeCAD 0.17 to be based on OCCT 7.2, but OCCT 7.3's planned release is at the end of April! Just one tiny example among many: with OCCT 7.2 it is possible to have perspective views in TechDraw, with lower versions it only produces a jumbled mess of edges.

WIth this info i will probably investigate the packaging process of `occt`, [this](https://salsa.debian.org/kkremitzki-guest/opencascade) will be a starting point, as it's going to be the debian package...

**Comment by karl-nilsson** [comment]
@Piraty thanks for the correction

**Comment by Piraty** [comment]
I made the PR: #13404
I really would like some feedback from other users!

**Comment by faulesocke** [comment]
This is done.
