### ISSUE TITLE
Package request: opera-ffmpeg-codecs

### ISSUE THREAD

**Issue by AcarBurak** [voidlinux/void-packages#12619]
Opera seems to need [opera-ffmpeg-codecs](https://www.archlinux.org/packages/community/x86_64/opera-ffmpeg-codecs/) to be able play some videos, for instance, anyone in http://www.independent.co.uk.
#12618

**Comment by cr6git** [comment]
Well, did you look at the [patches](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/opera-ffmpeg-codecs) used in Arch?
At least, we need to know whether they are needed.
I'm not qualified for this.

**Comment by AcarBurak** [comment]
I've seen, but not looked at them, as I wouldn't be able to understand what's going on!

**Comment by cr6git** [comment]
See [this commit](https://github.com/cr6git/void-packages/commit/ba1aeaf7712ea86f5b6c3e6ef0e3c3ad36c7d594) in my local repos...

Basically, I copied the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opera-ffmpeg-codecs) and added the 4 patches.

Do you want to test, @AcarBurak ?

Me I can't, because I'm currently on `x86_64-musl`. :black_joker:

**Comment by AcarBurak** [comment]
I won't have anything to do with Void.
I'm (or rather, was) fluxboxer you've censored just because I've laughed at a funny phrase ("Debian Bitrot Edition") of another poster, condemning my laughing as distro bashing rather than the original post which is innocent itself.
You would make a great dictator.

**Comment by thypon** [comment]
When did we start treating mental diseases?
