### ISSUE TITLE
virtualbox-ose-guest and virtualbox-ose-gues-dkms: DKMS build fails

### ISSUE THREAD

**Issue by alekseyt** [voidlinux/void-packages#12882]
### System

* xuname:  
  dmesg: read kernel buffer failed: Operation not permitted
   Void 4.15.12_1 x86_64 AuthenticAMD notuptodate rF
* package:  
  virtualbox-ose-guest-5.2.6_2
  virtualbox-ose-guest-dkms-5.2.6_2

### Expected behavior

Packages installed successfully

### Actual behavior

1) Installation fails
2) After DKMS build fails, package is marked as installed in XBPS

### Steps to reproduce the behavior

`sudo xbps-install virtualbox-ose-guest virtualbox-ose-guest-dkms`

It's some compilation error during DKMS build. I've bumped version to 5.2.8 and rebuilt mentioned packages using xbps-src and that worked for me.

I've also submitted pull request: https://github.com/voidlinux/void-packages/pull/12881 but travis build fails. I don't know why, travis log is truncated, but i've built it twice locally and build passes, so i thought i'll file an issue.

**Comment by Hoshpak** [comment]
I don't think the fact that the package is marked as installed is an actual issue. Installing an dkms package only installs the module source code and registers it with dkms. The building of the module via dkms is just a trigger that is run afterwards. If you have different kernel versions installed, it could succeed in building the modules for some of them and fail for others. So the real issue is that the module doesn't compile with current kernel versions.

**Comment by alekseyt** [comment]
> the real issue is that the module doesn't compile with current kernel versions.

Yeah, this was the reason why i opened the issue, the rest is just filling up issue template. The problem is that guest modules can not be installed into Void guest running on VirtualBox OSE.

**Comment by alekseyt** [comment]
I see that pull request is merged now, i reinstalled packages from repo and it worked for me, so i'm closing this issue.
