### ISSUE TITLE
Unable to install libgfortran: CONFLICT: cross-vpkg-dummy

### ISSUE THREAD

**Issue by RRvW** [voidlinux/void-packages#13319]
### System
Fresh install on a RPi3, with RPi2 glibc rootfs

* xuname:  
 `Void 4.9.51_1 armv7l  uptodate r`
* package:  
  * `openblas`

I'm unable to install `opencv`, it will fail with the following errors:
```
CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgcc-7.3.0_1 (matched by libgcc>=0)
CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libstdc++-7.3.0_1 (matched by libstdc++>=0)
CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg glibc-2.26_3 (matched by glibc>=0)
```
Looking through the debug log, it seems that libgfortran depends on `cross-vpkg-dummy` which conflicts with the libc and some other essential stuff.
Full log:
https://paste.pound-python.org/show/x90isr7siJB3jon26QPo/

### Steps to reproduce the behavior
 1. Download https://repo.voidlinux.eu/live/current/void-rpi2-PLATFORMFS-20171007.tar.xz
 2. Install on SD card with instructions from https://wiki.voidlinux.eu/Raspberry_Pi
 3. run `xbps-install -u`  twice
 4. `xbps-install libgfortran`

**Comment by newbluemoon** [comment]
The problem is that libgfortran cannot be cross compiled and therefore isn’t available in the repo for arm*.

You’d have to compile that package yourself on your Pi. I did that not so long ago and if I remember correctly it took about 20 hours on a Pi3. ;)

However, openblas has gcc-fortran in `hostmakedepends` so I guess that’s why there’s a cross package. But when generating the dependencies I think it adds cross-vpkg-dummy because it’s the only package available which provides libgfortran. I’m just wondering how can it link to libgfortran when it’s not available in the first place; does it link to the host libgfortran?

**Comment by newbluemoon** [comment]
Tested with a natively built libgfortran (armv7l-musl) the installation of openblas went just fine.

The cross-compiler packages <i>do</i> have libgfortran. That’s why openblas can be linked against it. However, when cross compiling the gcc suite libgfortran cannot be built currently so that when installing openblas on a cross platform and in the absence of libgfortran it tries to pull in cross-vpkg-dummy which also “provides” libgfortran.

@pullmoll I’m wondering if the `libgfortran.so.*` from the cross-compiler packages could be used and made into a standalone libgfortran package for those platforms? Or is this a bad idea? And I don’t know of how much use a libgfortran would be without the gfortran compiler in general.

**Comment by pullmoll** [comment]
@newbluemoon I was stuck back when trying to cross build `fortran` in the `gcc` package, because some files were created based upon the host architecture, running scripts in the host, which actually would need to be tailored for the target.

I was not successful getting this to work, which is why we now have the situation that you can cross compile with gfortran, but the libfortran is missing for the cross target architectures.

The problem with the idea to create a cross package from a native build of e.g. `cross-aarch64-linux-gnu` is that AFAICT you just can't. You have no way to make `xbps-src` create a package for another architecture but the one being the currently *active* (i.e. host or target).

The proper solution would be to fix `gcc` cross builds to also build `gcc-fortran` and `libgfortran{,-devel}`. Perhaps we could replace the (wrongly) generated intermediate files with some pre-built files for the target architectures. I don't exactly remember what files that were, but it isn't too hard to try.

Just make sure the gcc template adds `subpackages+=" gcc-fortran libgfortran-devel libgfortran"`  and `_langs+=",fortran" for cross builds and see it fail at some point.

**Comment by newbluemoon** [comment]
So I modified the template as you suggested and also added

    export GFORTRAN_FOR_TARGET="${XBPS_CROSS_TRIPLET}-gfortran"

(that was before I found that there is an `FC` variable)

And now the build finishes and all packages are built. Could the solution be that simple or am I missing something?

**Comment by newbluemoon** [comment]
Comparing the cross with the natively built gcc-fortran package (armv7l-musl) the former misses
`/usr/lib/gcc/armv7l-linux-musleabihf/7.3/finclude/`

**Comment by pullmoll** [comment]
@newbluemoon Oh, that could explain why it worked for you! I had a `hostmakedepends+=" gcc-fortran"` and thus the host fortran was used to cross compile..

I'll give it a try when I'm back from a therapy in the afternoon. It looks like it could really be that easy.

**Comment by pullmoll** [comment]
For the `/usr/lib/gcc/${XBPS_CROSS_TRIPLET}/${version%.*}/finclude` this is probably just an omission in the cross-* templates. The do_install() of these packages is rather complicated.

**Comment by newbluemoon** [comment]
@pullmoll Glad if I can help. :)
