### ISSUE TITLE
glew-devel: missing dependency on glu-devel in arm*?

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1428]
When trying to build a project with both `glu-devel` and `glew-devel` in makedepends, xmindep tells me that glu-devel is redundant. The entire `makedepends="boost-devel minizip-devel glu-devel glew-devel SDL_gfx-devel SDL_image-devel SDL_net-devel SDL_mixer-devel SDL_ttf-devel lua51-devel"`

After removing `glu-devel` and cross building the project for `armv6hf` or `armv7hf`, the build fails when it tries to include `/usr/include/GL/glu.h`, which does not exist at this point. Cross building for `i686` on the other hand works as expected.

Keeping `glu-devel` in makedepends I can cross build on `armv7hf`... and `armv6hf`.

To me this looks like the dependency on glu-devel is missing from the arm* glew-devel package for some reason?
Edit: It is not in glew/template at all, so it looks like it is in some other package, which causes xmindep to tell its redundant, while on arm* that other package doesn't require glu-devel... strange.

**Comment by chneukirchen** [comment]
`xmindep glu-devel glew-devel` does not reduce further here both on x86_64 or armv7.

However, I can reproduce with `xmindep glu-devel glew-devel SDL_gfx-devel`. This is because on x86_64, SDL depends on libGL but on armv7 it doesnt (because there SDL is built with `~opengl`).  Just keep glu-devel as a dependency...

**Comment by pullmoll** [comment]
Thank you for the clarification.
