### ISSUE TITLE
Package Request: zynaddsubfx

### ISSUE THREAD

**Issue by spectromas** [voidlinux/void-packages#2656]
Would be great to have this packaged if possible - http://zynaddsubfx.sourceforge.net

**Comment by pullmoll** [comment]
This is a little more difficult than I expected because of [mxml](http://mxml.sourceforge.net/).

I first tried to package `libmxml-0.9.1` which required some patches, because it doesn't build out of the box (missing system includes `stdlib.h` and `string.h` in `mxml.h`). Unfortunately zynaddsubfx expects a typedef for `mxml_node_t` which `libxml-0.9.1` does *not* define.

So zynaddsubfx won't work with my packaged libmxml-devel-0.9.1_1

Then I tried to package `libxmlplus-0.9.2` which also failed: some sources do not know `m_node`, which is  a member of the Node template class. This may be compiler related. The source is old (2004).

I'm not sure how to fix this situation. I think there must be some patches to libxml-0.9.1 to make it define the types that `zynaddsubfx` expects.

Too bad `zyaddsubfx` didn't include a working `3rdparty/libmxml` or similar, because this old library (2003) is troublesome.

**Comment by spectromas** [comment]
Hi pullmoll, sorry to hear you have already been through so much trouble without any success on this. I wasn't expecting it to be so complicated. 

I was just looking at the [gentoo ebuild](http://data.gpo.zugaina.org/gentoo/media-sound/zynaddsubfx/zynaddsubfx-2.5.1.ebuild) and it appears to be using the source from here for [mxml](http://www.msweet.org/projects.php?Z3) with provides 2.9. I don't know anything about this package though, is it the same one that you're looking at here?

**Comment by pullmoll** [comment]
Yep. I also looked around and saw there is another mxml at http://www.minixml.org/
I'll try to go with that one and see if I can zynaddsubfx packaged.

**Comment by pullmoll** [comment]
That was easy in comparison. I should have looked which is the required mxml first, that would have saved me some headache :)

**Comment by spectromas** [comment]
Thanks so much, can't believe this was done so quickly!
