### ISSUE TITLE
tzdata: armv7hf-musl extraction error

### ISSUE THREAD

**Issue by Duncaen** [voidlinux/void-packages#2688]
```
[*] Running transaction tasks
tzdata-2015f_1: updating to 2015g_1 ...
tzdata-2015g_1: unpacking ...
ERROR: tzdata-2015g_1: [unpack] failed to extract file `./usr/share/zoneinfo/right/America/Kralendijk': I/O error
ERROR: tzdata-2015g_1: [unpack] failed to extract files: I/O error
ERROR: tzdata-2015g_1: [unpack] failed to unpack files from archive: I/O error
```

**Comment by pullmoll** [comment]
Strange. The archive `http://muslrepo.voidlinux.de/current/tzdata-2015g_1.noarch.xbps` seems ok. In can run the command `tar tvf tzdata-2015g_1.noarch.xbps` without errors, and also extracting works.

Perhaps your copy in `/var/cache/xbps` is broken for some reason?

Otherwise it may be caused by libarchive for armv7hf, which xbps depends on AFAIK.

**Comment by chneukirchen** [comment]
Check dmesg to see if this was not a hardware error.

**Comment by xtraeme** [comment]
This sounds like a hardware issue.

**Comment by xtraeme** [comment]
EIO errors are usually returned by the hardware to the filesystem layer and then to userspace.

I would check for damaged sectors or inconsistencies in the filesystem.

**Comment by Duncaen** [comment]
Your right, the sdcard in my rpi2 is corrupt.
Manually extracting it on the system works too.
Tanks for your help.

I can't get the rpi to boot with pass enabled in /etc/fstab, is this my fault or should it work with pass 1?
```
/dev/mmcblk0p3 / f2fs defaults 0        0
```

**Comment by xtraeme** [comment]
f2fs.fsck does not seem to support a flag required by fsck -a. Setting passno to 0 is ok.

**Comment by thypon** [comment]
Solved?!
