### ISSUE TITLE
base-files: something is funky with this package in musl repo

### ISSUE THREAD

**Issue by xaduha** [voidlinux/void-packages#2836]
Related https://github.com/voidlinux/void-mklive/issues/40

Installing base-files (non musl) in a folder works fine, but musl version creates just 3 folders.

**Comment by Duncaen** [comment]
Thats because the install steps are skipped while using a different `XBPS_TARGET_ARCH` because it wouldnt work on your host architecture.
If the host is x86_64 and the target is x86_64-musl you can chroot into your target folder and run `xbps-reconfigure -a` to do the last steps. If its another architecture like arm you need to use qemu.

**Comment by xtraeme** [comment]
When setting `XBPS_ARCH` or `XBPS_TARGET_ARCH` environment variables, the configuration phase is skipped because the target binaries might not be executed for the native architecture.

The `configuration` phase must be run via `xbps-reconfigure(1)`.
