### ISSUE TITLE
Package Request: btpd,lel

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#3078]
i have a package request for btpd, farbfeld and lel
https://github.com/btpd/btpd
http://git.2f30.org/farbfeld/
http://git.2f30.org/lel/

**Comment by FRIGN** [comment]
Hello,

I'm the author of farbfeld and working in the team that developed lel.
Please note that farbfeld has moved to http://git.suckless.org/farbfeld. I am going to tag a release soon to make package distribution easier.

With best regards

FRIGN

**Comment by Duncaen** [comment]
Added farbfeld in ec28a27

**Comment by kojicomics** [comment]
The latest version of lel (v0.1) was released in 2015.
Since 2016, farbfeld support has been added along with some updates, but a new version hasn't yet been released.
I will try to contact the main developer to see if they can tag a new release with these changes.

About btpd, we have been discussing here #10749  that it is better to ignore this package, since its current state is useless.

**Comment by maxice8** [comment]
lel was added, this can be closed i assume.
