### ISSUE TITLE
 Package Request: dwmstatus,dmc

### ISSUE THREAD

**Issue by xcelq** [voidlinux/void-packages#3079]
http://git.suckless.org/dwmstatus/
http://git.suckless.org/dmc/

**Comment by Duncaen** [comment]
I don't see the point of packaging `dwmstatus`, it only shows the loadavg and 3 different timezones.
Its clearly just a template you have to customize, if you want the loadavg and 3 timezones in your statusbar a shell script is perfect for that.
`dmc` has no releases and there is not even a small change since 5 years.
