### ISSUE TITLE
Package Request: Visual Studio Code

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#3208]
Source releases available here: https://github.com/Microsoft/vscode/releases

it depends on electron and node

**Comment by skrzyp** [comment]
Oh, really? It's just a wrapped Chromium with some HTML5/Javascript pseudo-editor, it has nothing to actual Visual Studio, except the name…

**Comment by dominikh** [comment]
@skrzyp how is that relevant to this issue/package request? The request is for a software called "Visual Studio Code". Whether "Visual Studio Code" has anything to do with "Visual Studio" or whether it's a software to control your coffee maker with is irrelevant. 

This issue warrants no personal opinions on the software.

**Comment by nickolasacosta** [comment]
someone should do this...

**Comment by davidpaulos** [comment]
at least we have atom but yes we do need vscode

**Comment by Duncaen** [comment]
There is currently no maintainer for atom, the atom template is limited to `x86_64`, `i686` and wouldn't work with musl without heavy patching, same goes for a potential template for `vscode`.
Electron based programs have a very high maintenance burden because there is no shared electron runtime and it needs to be completely rebuild from source for each program. This makes it a time and resource consuming task for maintainers and build servers.

**Comment by davidpaulos** [comment]
understood. then i should tell everybody that despite not being in the repos vscode does exist as an appimage as such i would suggest that we use that instead.
just make a symbolic link thanks for the speedy reply

**Comment by Yardanico** [comment]
@maxice8 this can be closed

**Comment by maxice8** [comment]
On Sat, Nov 17, 2018 at 03:20:51PM -0800, Yardanico wrote:
> @maxice8 this can be closed
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/issues/3208#issuecomment-439654917

I don't have rights on the voidlinux organization
