### ISSUE TITLE
Package request: docker-machine

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#3261]
https://github.com/docker/machine

(Go program)

**Comment by dominikh** [comment]
To whoever ends up packaging this: You will want to modify the Go
build-style and export GO15VENDOREXPERIMENT=1 -- or just wait for Go
1.6 to be released.

Apart from that, you will need to overwrite do_install, because Docker
structured things poorly and the binary will be called "cmd" -- so
rename that.

Apart from that, however, packaging this should be fairly trivial --
fetch the tarball, import path is github.com/docker/machine, package
is github.com/docker/machine/cmd

Good luck, and thanks to Docker for adding their own build system on
top of Go's :-)

**Comment by radare** [comment]
Maybe just the https://github.com/voidlinux/void-packages/pull/3304 binary pkg until Go 1.6 is released.
