### ISSUE TITLE
Kodi fails to load on i686

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#3302]
Kodi does not start on i686 failing with the error message:
```Unable to find path to Kodi data files!```

Kodi works fine on x64 with no issues.

**Comment by Hoshpak** [comment]
My findings so far:

If configure is called with libdir=/usr/lib, the kodi binary searches for the userdata in /usr/lib/kodi/userdata and doesn't find it there. It continues to search for it in /usr/share/kodi/userdata, finds it and starts up.

If configure is called with --libdir=/usr/lib32 (which is currently used on i686 through $configure_args) however, the resulting binary stops looking after failing to find /usr/lib/kodi/userdata, displays the error message and terminates.

I couldn't find a significant difference between the produced binaries yet that could explain the different behaviour but I will keep looking. On x86_64 --libdir is omitted which could explain why it works there without issues.

**Comment by Hoshpak** [comment]
I did some more digging into the kodi source code (particularly xbmc/Util.cpp and xbmc/Application.cpp since the directory detection happens there) yesterday but could not find out why exactly the detection fails if the binary is configured and compiled with --libdir=/usr/lib32. Since the source code relies on the environment variable KODI_HOME, manually setting this variable in the startup script to /usr/share/kodi would be another workaround that would allow kodi to start up on Void i686 installations.

Since I didn't find a proper bug tracker or other means of contacting the kodi developers, I created a [thread](http://forum.kodi.tv/showthread.php?tid=282925) on the kodi forums. I hope someone who understands their C++ code better than me will look into it and will be able to costruct a proper fix for the userdata directory lookup code.
