### ISSUE TITLE
No Consensus on Font Packages

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#4649]
Can we please come to an agreement on what sorts of font packages we will or will not install? What about themes? Can we please decide this and either merge or reject the multiple relevant PRs in the list?

**Comment by gotwf** [comment]
Themes are more DE centric so less of a concern to me.  Tweak your desktop theme to your heart's desires.

Fonts, otoh, are more system wide and seem to be a 'weak' area to me on void.  Well, I guess themes could be considered system wide too but in bit less generic sense.  If you're running X, you deal with fonts.  But you don't necessarily deal with gnome themes if you're on KDE.  Themes are also mostly 'eye candy' aesthetics whereas fonts affect readability and usability so it "feel's" a bit different argument to me at least.

In any case, I would prefer having more rather than less granularity over my font choices in that, for e.g. as mentioned in issue #4436, I could install Noto fonts w/o having to pull in a multitude of other google fonts that I will never use.

My $0.02.  

Peace.

**Comment by halfwit** [comment]
I'm mostly interested in the simplicity of updates, so long as the people putting in the PRs are doing their legwork to make this happen the issue with fonts may impede only convenience

**Comment by chneukirchen** [comment]
I don't see harm in packaging widely used fonts.

**Comment by Vaelatern** [comment]
I understand the fear of "That weird distro where I installed this stuff through my package manager despite it really belonging in `~/`" as well. Personalization of non-compiled assets may best be done in `~/`

**Comment by kurumushi** [comment]
I don't think it's an issue of things being installed in /usr when they should be in ~/, I think it's an issue of "why do I need to install two hundred things to get the one that I want"

I agree that that googlefonts package is huge. I think from a general standpoint, it's better to split it up into individual packages for the popular fonts, and let users install the rest. I'm not sure of the reason that the original creator made it monolithic.

If anything, fonts and themes should have a guideline of one font/theme per package. googlefonts is currently a single template that installs hundreds of different fonts, so it would be out. It should be split into a few packages that cover the most popular fonts (roboto and noto). With possible subpakages within those for the larger variants. For example many distros have a noto package with the core fonts, and then a noto-cjk which installs the asian character fonts. This way would mean more packages and would take more work, but I feel like it's the better way to go.

As far as which fonts and which themes to include, that kind of depends on what void aims to be. Does it want to have all the popular stuff in a main repo, and depend on others for extras? Does it want to include as many packages as possible? Fonts and themes are generally pretty easy to package.

**Comment by Vaelatern** [comment]
Should xbps be in the market of being a place to install things for your system?

**Comment by Vaelatern** [comment]
#4580 and #4581 seemed reasonable except that we don't have a consensus.

**Comment by Vaelatern** [comment]
#4586 as well

**Comment by gotwf** [comment]
On Wed, 24 Aug 2016 12:35:26 -0600,
Toyam Cox wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> Should xbps be in the market of being a place to install things for your system?

I am not a dev and relative newbie to Voidlinux so do not want to be
perceived as a Johnny Come Lately trying to "bend" the old guard to my
will.  I offered my opinion on this issue in the first place because
it seemed to me Vaelatern was soliciting such from broader Void users
camp.  I have tried to take perspective of lesser experienced user and
play devil's advocate a bit as well.  If I am treading on any toes
here feel free to disregard and there will be no hard feelings.

With the above in mind, I have had some discussion of this 'larger
picture' both inside and outside of void as of late.  Not a lot but
follows are a few thoughts:

1. Themes and fonts are kind of apples and oranges in my view and
should not necessarily fall under same umbrella policy.

2. Themes are DE centric and specific.

3. Themes are pure eye candy w/exception that you do need at least one
theme to launch your DE.  Most DE's come bundled with something as
current 'default' theme so you can get up and running on a new DE
install.

4. After which, most DE's have some mechanism to install themes.  It
has been many years since I have used a full blown DE, however, so I
am happy to stand corrected if such is not the case in more modern
times.

5. Themes pull in tons of icons and other small files and, as some
have expressed, potentially 'pollute' package manager indexes with
many permutations of this, that, and the other persons variations on a
theme.  This reportedly has the potential to negatively impact both
performance and search queries.

Archlinux and pacman were independently referenced by a couple folks I
was discussing this with as an example of how not to do it.  I present
that here in that context, not as a bash against Arch.  I don't have
any hard numbers but can attest that pacman db updates 'feel' slower
than e.g. 5-6 years ago.  Not saying that correlation has anything to
do with causation but maybe something for those more knowledgeable
than I to ponder.

6.  Fonts are more broadly scoped and hence of more value to wider
range of users than a DE theme.

7.  At least one set of fonts must be present to even get to a
graphical state.  Unlike DE's, there is no mechanism for any consensus
as to what fonts this may be, but I suppose it could be argued that
DejaVu may well fill this role.

8. Fonts, while from stylistic perspective may also be labeled as 'eye
candy', also fill a more functional usability role
w.r.t. considerations such as internationalization, readability, etc.
And this is the primary role in which I view them (as contrasted for
e.g. 4K different fonts for a desktop publishing set up).

9.  Although simple enough to install on per user basis, there is no
simple gui clickery to facilitate font installation for less
experienced users like there is for DE's.

I have yet to draw any firm conclusions from this analysis.  I'd like
to have a few more popular fonts such as Noto Sans/Serif available
without having to pull in a few hundred other fonts in what is
essentially a huge metapackage.  However, I am happy to give up this
minor convenience if it meant I also had to put up with a bazillion
themes and icon packages for every DE out there.

Peace.

**Comment by Vaelatern** [comment]
With that, I think we should merge the japanese and hebrew font sets currently in PRs, as well as any other reasonable font package that provides something we don't yet have. Font packages that provide other fonts should be discussed and if too large or not interesting enough for some reason, rejected.
Themes, unless they provide good functionality we would not otherwise have, should be rejected and installed through other means on a per-user basis.
Thoughts?

**Comment by halfwit** [comment]
I'm on board with that,  @Vaelatern

**Comment by kurumushi** [comment]
That sounds good to me. Keep the major fonts and themes that are usually required for compatibility (adwaita, oxygen, liberation, ...) and also very popular ones (noto, roboto, ...) in the main repo. Void is a relatively small distro at the moment, and adding everything under the sun doesn't feel like the best direction at the moment.

Another option not spoken of yet would be to create an optional "extras" or "community" repo, with less strict rules on what can get in.

**Comment by awalGarg** [comment]
New to void here.

> Another option not spoken of yet would be to create an optional "extras" or "community" repo, with less strict rules on what can get in.

Sort of a :+1: on this - but then I guess we'd be shifting concerns from one place to another - since we'd have to come up with the "less strict rules" for *those* repos.

**Comment by Vaelatern** [comment]
No. Void is not interested in a repository with poor quality.

**Comment by ebfe** [comment]
> Personalization of non-compiled assets may best be done in ~/

I really don't understand the "you can easily install it manually to ~
yourself" argument. Why is it better to manually hunt down updates and copy
files to various places in ~ than just using a package?

"That wired distro where I have to install a lot of things manually because
they refuse to use their excellent package manager" ;)

**Comment by gotwf** [comment]
1. Fonts rarely require updating once installed so they're pretty much set and forget.
2. Historically on multi user systems mortal accounts needed a means for such personalization w/o requiring root privileges.  
3.  I think it is important to keep in mind the context here.  Extending personalization of fonts and themes to "a lot of things" seems a bit of a leap.

I think there has also been competition amongst commercially marketed distros for a high package count for sales types to brag about.  Hence, some distros package hundreds upon hundreds of e.g. perl, python, ruby, etc. modules so as to boost package count numbers when in reality these are most likely to be managed via gems, etc.   And that kind of set a precedent that a lot of other distros followed w/o giving it much analysis.  But is this a good thing?

The more I ponder this issue the more I am leaning towards playing it conservatively.  

Just some thoughts.  See first paragraph of my tl;dr post above ;)

**Comment by kurumushi** [comment]
I didn't mean that any extra repo created would be of lower quality. I just meant that it could hold packages not seen as essential or mainstream enough for the main repo. I guess based on #2 of what @gotwf said, it raises another question on what kind of distro Void aims to be. Most desktop distros assume only one or two trusted users, in which case it would be for convenience that themes and fonts would be packages, because most users could probably install easily from the package manager. But if void is trying to be more server or multiple user workstation oriented, it would be the better choice to leave all of the customization to the user.

And in reply to what @gotwf  said about high package count, even though it's going a bit off topic: I hate secondary package managers (gems, pip, npm) like the plague. A system should consist of a single package manager and manually installed packages, not a different package manager for every programming language. I don't want any third party manager installing packages of questionable origin and quality in my /usr. I could care less about high package count, but I think that "it can be installed by gems/pip/whatever" is not an excuse to forgo making a package that is tested for quality and compatibility with your distro.

**Comment by lemmi** [comment]
I agree with @kurumushi and find a single package manager so much more convenient especially when the rest is such crap. (I'm looking at you, tlmgr).
Anyway. Does packaging fonts hurt people that do want to install fonts themselves? So why not add a font when there's a contributor for it. I don't care for package count, I only care how easy it is for me to get something up and running. For me that's through xbps and that's the reason I'm here after all. 
I'd even like to have a meta package for all-the-fonts because I'm sick of either installing everything by hand or staring at boxes with numbers in it. 

Merge all the fonts.

**Comment by halfwit** [comment]
Not gonna lie, seeing something like 'Merge all the fonts' makes me wonder if you've ever built a meta-fonts package regularily. It moves fucking fast, and I've no want to be downloading stupid font changes over a stupid font I never use, each ~2.5 days. Sure, if you guys want a meta package, go hard. But don't touch what is there, and works.

**Comment by lemmi** [comment]
1. People maintain packages voluntarily, so I assume they really want a certain package and are fine with putting some work in it, so others don't have to. So if there's no demand for a certain font and nobody will step up, it will not land in the repo.
2. Why do you install packages you don't use or find annoying?

I still really see the problem. Looking at how contributors work anyway, you'll get updates rather every few weeks than in that frequency. The only reason I can think of where this is a problem is when you are on a metered line, but then again you probably chose the wrong distro. Our buildservers are not at full capacity so they couldn't handle another font package or two, so that's no issue, too.

There are tons of packages you probably don't use and still get updated and I'd be surprised if that was a problem so far.

**Comment by kurumushi** [comment]
I don't see any problem with virtual or meta font packages that would depend on individual fonts. A mega package that contains lots of fonts I do agree is a bad idea. The current google fonts package is a great example. It's about 150MB in its current state. It doesn't see frequent updates, but I don't think I want to download a 150MB package every time a change is made to a single font in it.  As I stated above I think 1 package should equal 1 font (family.) 

I think we're getting lost in details here though. The main issue at hand is if void should include lots of font and theme packages, or if it should keep to basics only. Other details about how to handle them can be debated later.

**Comment by asergi** [comment]
What @chneukirchen said. Can we please close this non-issue?

**Comment by Vaelatern** [comment]
Resolved thus: Widely used fonts are fine, other fonts are possibly okay depending on quality of the package, on a per-instance basis. If it can be installed locally and is not widely used, merges may vary.
