### ISSUE TITLE
Surprising behavior: xbps-query -R -o "*/xlocate"

### ISSUE THREAD

**Issue by stevelitt** [voidlinux/void-packages#4773]
The following symptom description uses xlocate as an example, but use of any filename triggers this unexpected behavior...

xbps-query -R -o "*/xlocate" produces no results, contrary to the behavior described on the document https://wiki.voidlinux.eu/XBPS#xbps-query . 

xbps-query -o "*/xlocate" (without the -R for Repository) correctly reports /usr/bin/xlocate and the package it belongs to. According to the above listed document, that should also be the output with the -R.

This is a significant inconvenience because I need to do a search of "what package must I install in order to get file xlocate?"

I'm using X64 Void Linux, up to date as of four days ago.

**Comment by ebfe** [comment]
```
$ xbps-query -R -o '*/xlocate'
xtools-0.43_1: /usr/bin/xlocate (regular file)
```

It's pretty slow though.

**Comment by Vaelatern** [comment]
Your problem is possibly one of shell substitution. `"*/xlocate"` tells your shell to interpret the `*` itself, which is likely to give unreproducible results. `'*/xlocate'` tells your shell to do no interpretation at all. It is possible your shell is not actually exchanging values for the `*` in the former case, but you should be aware of the distinction between double and single quotes.

**Comment by stevelitt** [comment]
First, I'm sorry for having used doublequotes when the documentation clearly called for singlequotes. As it turns out, on my computer, with bash, dash or sh, the results with singlequotes are the same: no output. If I remove the -R, I get the correct output.

Ebdf and I have this problem in a Judo hold. xbps-query -R -o '*/xlocate' works as advertised on his system, but presents no output on mine. All we need to figure out is how our systems are different.

Here's my situation:
$ uname -a
Linux mydesk 4.6.6_1 #1 SMP PREEMPT Wed Aug 10 15:53:03 UTC 2016 x86_64 GNU/Linux
$ 
$ xbps-query -L
 6963 https://repo.voidlinux.eu/current (RSA signed)
   23 https://repo.voidlinux.eu/current/multilib/nonfree (RSA signed)
 2927 https://repo.voidlinux.eu/current/multilib (RSA signed)
   42 https://repo.voidlinux.eu/current/nonfree (RSA signed)
 3851 https://repo.voidlinux.eu/current/debug (RSA signed)
$ 

If we can figure out what's different about our systems, we have a good shot at understanding this anomoly.

**Comment by Duncaen** [comment]
You could try `xbps-query -Rdo '*/xlocate' 2>locatelog` on the failing system, i think this log would be huge, but the only way to find out what really happens.

**Comment by pullmoll** [comment]
> First, I'm sorry for having used doublequotes when the documentation clearly called for singlequotes.
I changed the Wiki only after your report. It is true that there were doublequotes before.

**Comment by chneukirchen** [comment]
Shell quoting makes absolutely no difference here, please learn those rules people...

**Comment by pullmoll** [comment]
D'OH! :blush:

**Comment by zqqw** [comment]
Same behaviour here, also:
~$ xbps-query -Ro '*/xterm'
~$ xbps-query -o '*/xterm'
adwaita-icon-theme-3.20_1: /usr/share/icons/Adwaita/cursors/xterm (regular file)
ncurses-base-6.0_2: /usr/share/terminfo/x/xterm (regular file)
vte-0.28.2_14: /usr/share/vte/termcap-0.0/xterm (regular file)

I don't have the sshd service enabled though, possibly something like that is blocking the connection? I can do xbps-query -Rs pkgname for uninstalled packages while offline, so that -R must be looking in a local list, not online.

~$ xbps-query -Rdo '*/xlocate' 2>locatelog
(Complete output)
[DEBUG] XBPS: 0.51 API: 20151030 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] /etc/xbps.d: ignoring .empty
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
[DEBUG] [repo] `https://repo.voidlinux.eu/current' stored successfully
[DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://repo.voidlinux.eu/current
[DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg awk for gawk
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg cron-daemon for dcron
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg editor for nvi
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg man for openbsd-man
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg ntp-daemon for openntpd
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg openssl for libressl-openssl
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg shell for dash
[DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg smtp-server for opensmtpd
[DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: i686
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://repo.voidlinux.eu/current
[DEBUG] [rpool] `https://repo.voidlinux.eu/current' registered.
[DEBUG] Adapta-3.21.5.88_1: couldn't fetch files.plist from https://repo.voidlinux.eu/current/Adapta-3.21.5.88_1.noarch.xbps: Success

**Comment by Duncaen** [comment]
@zqqw -Ro can't work offline, its different from -Rs, -o needs to download the the package to get the files list, -s can just use the local repodata.

**Comment by zqqw** [comment]
Going to the address https://repo.voidlinux.eu/current in my browser I see:
Adapta-3.21.6.19_1.noarch.xbps
Above:
Adapta-3.21.5.88_1.noarch.xbps
I think an xbps-install -Syu could be what I'm missing, I'll try it when I have time!

**Comment by zqqw** [comment]
Yay! It works now!
$ xbps-query -Ro '*/xterm'
adwaita-icon-theme-3.20_1: /usr/share/icons/Adwaita/cursors/xterm (regular file)
^C
(I got bored before it finished)
Presumably this gets updated very frequently and the version info needs refreshing just before use.

**Comment by ebfe** [comment]
That might actually be the answer.  If `xtools` was updated between the last sync (`xbps-install -S`) and the query `xbps-install -R -o '*/xlocate'` the package might be skipped since it's no longer available in the repo and so no results. @stevelitt care to try again after a sync?
