### ISSUE TITLE
phonon{,-qt5}-backend-gstreamer: build broken

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4813]

**Comment by pullmoll** [comment]
There are several things causing this:
+ The `phonon-qt5-backend-gstreamer` template needs hostmakedepends + `extra-cmake-modules`
+ hostmakedepends `cmake` is redundant
+ There is a header file `/usr/lib/gstreamer-1.0/include/gst/gstconfig.h` in `gstreamer1` which as it seems needs to be moved to `/usr/include/gstreamer-1.0/gst/gstconfig.h`, because this pkg tries to include it.
