### ISSUE TITLE
qt5 host tools

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4891]
The arrangement of qt5 tools is bad for cross-compilation, while qmake is in qt5-qmake, e.g. uic is only in qt5, so you have to install whole qt5 on the host.

**Comment by pullmoll** [comment]
Agree. Furthermore we should have `cross-qt5-qmake-$arch` which exists while building qt5 for a cross arch, but is not packaged. This is a qmake for the host which has all values set for the cross arch.

I don't know if then these qmakes should become a cross-vpkg-dummy entry, or what else could be done to automagically use the required `cross-qt5-qmake-$arch` package in the qmake build style.

**Comment by pullmoll** [comment]
The packages that should go into `qt5-tools` or perhaps a new `qt5-host-tools` are the ones which are compiled twice, once for the host and once for the target: `qmake`, `moc`, `rcc`, `uic`, `qlalr`, `qdbuscpp2xml` and `qdbusxml2cpp`.

**Comment by chneukirchen** [comment]
+1 for making build_style=qmake add the correct hostmakedepends.

**Comment by pullmoll** [comment]
I'll try to package the target specific qmakes and then create a `common/environment/build-style/qmake.sh` which adds the required one to the hostmakedepends.

This will take some time because it requires testing all arches...

**Comment by pullmoll** [comment]
I just realized this can't work because when compiling for `-a aarch64` I can't create host packages :frowning_face: 

The only way I see is to create a number of `cross-$XBPS_CROSS_TRIPLET-qt5` or `qt5-qmake-$XBPS_CROSS_TRIPLET` packages which create the target specific qmake via the bootstrap stage of qt5, just like `srcpkgs/qt5/template` does now. This involves creating a `mkspecs` entry with a `qmake.conf` for the cross compiler, linker, flags etc.

The packages would then have `conflicts="qt5-qmake>=0"` and be used instead of this in the build style qmake.

I'll see if I can make these templates use the version, distfile, checksum etc. info from the qt5 template.

**Comment by chneukirchen** [comment]
Aren't these tools portable enough that we can run the host version when compiling for the target?

**Comment by pullmoll** [comment]
The problem is with specifying the `-xplatform` or the `-device some-device-name` and `-device-options CROSS_COMPILE=${XBPS_CROSS_TRIPLET}-`. I have not found a way to tell these to a qmake built for e.g. x86_64.

These options are passed in the `./configure` before qmake is built.

Perhaps there is some way like a generated specs file (?) to make qmake respect these additional or alternate options.

**Comment by chneukirchen** [comment]
I just added code to pass CC and CXX directly to the Makefile and that seemed to work so far... ;) a91c8dc

**Comment by pullmoll** [comment]
Ok, then perhaps this is sufficient. Did anyone test the pkg created on the specific hardware, e.g. raspi?

**Comment by chneukirchen** [comment]
We have this now.
