### ISSUE TITLE
Package request: Telegram Desktop client

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#515]
https://github.com/telegramdesktop/tdesktop

**Comment by silvernode** [comment]
I was going to request this but it looks like it's already here. I use telegram daily, if someone could package it that would be awesome.

**Comment by Duncaen** [comment]
"Qt 5.4.0, slightly patched" stopped me from packaging and instead using the webapp.

**Comment by silvernode** [comment]
forgot I was here before, tried requesting this myself. Has anyone tried packaging this again? Maybe it will work now.

**Comment by Duncaen** [comment]
It still uses a patched QT version and doesn't provide versioned sourcecode archives.

Maybe we can take a look at https://github.com/voidlinux/void-packages/issues/921 they released a second beta of the first 1.0 release.

**Comment by silvernode** [comment]
Arch Linux seems to pull in something called Qt everywhere. Not sure if this will help or not. 

https://aur4.archlinux.org/packages/telegram-desktop-git/

**Comment by JustDevZero** [comment]
Qt-Everywhere is the Qt download from official QT, that is not necesary the the one in repos...
Mixing Qt versions is always a bad idea.

Also, there is also Cutegram from Aseman:
http://aseman.co/en/products/cutegram/

License is GPL3 and it's build in QT, maybe it can be packaged instead of tdesktop.

**Comment by Duncaen** [comment]
@JustDevZero nice find, I can create a package for this later today.

Curegram has tagged releases (Y) https://github.com/telegramdesktop/tdesktop/issues/367 not yet.

**Comment by jprjr** [comment]
Just thought I'd let anybody interested know - there's now a libpurple plugin for Telegram. See #3548

**Comment by silvernode** [comment]
Looks like tdesktop has tagged releases now thanks to you @Duncaen

**Comment by ibrokemypie** [comment]
@silvernode does that mean this can be packaged now?

**Comment by ibrokemypie** [comment]
@Duncaen the "slightly patcched" is referring to the version of LGPL that qt uses,not the qt itself

**Comment by vaartis** [comment]
What about the way telegram deals with dependencies? It seems to ignore system-wide ones and only use those in `../Libraries`, including big things like Qt

**Comment by vaartis** [comment]
Should we use their binaries or build from source? Note, that if we are going to build from source we should also create templates for the following packages: 
`appindicator unity dee libxcb-image libxcb-keysyms libxcb-icccm libxcb-render-util libxcb-util libxcb-sync libxcb-xfixes libxcb-randr libx11-xcb breakpad` and patched Qt
Also note, that for musl libc, crash reporting must be disabled, because breakpad is mostly glibc-oriented

**Comment by Vaelatern** [comment]
libappindicator is now in the repo!
So that's one down.

**Comment by maxice8** [comment]
telegram-desktop is in the repos.

**Comment by silvernode** [comment]
Yeah this needs to be closed, one less backlog item
