### ISSUE TITLE
Package Request: flaskbb

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#5203]
A forum software based on flask.

https://flaskbb.org
https://github.com/sh4nks/flaskbb

**Comment by Duncaen** [comment]
I don't see how or why this should be packaged.
The package would enforce too much other things like the webserver and its configuration.

**Comment by Anachron** [comment]
I don't get it. Why is flask packaged and flaskbb not? flaskbb ist just an application on top of flask.

**Comment by Duncaen** [comment]
How should we automatically handle updates, should it run `python manage.py db upgrade` automatically?
Packaging such web applications sucks, they are too fragile to update automatically, its really easier and safer for you as an administrator to install a virtualenv and do updates and migrations manually.

**Comment by Anachron** [comment]
Hmmm I believe it would be good to update the packages by xbps and run the migration and other stuff manually.

But if there are no tagged releases I guess it cannot be included in main repo?

Is there any information on why pkgs cannot be based on a commit-hash?

**Comment by Vaelatern** [comment]
Because commit hashes are often intermediate quality software, not deemed worthy of a release by upstream. Also because people keep bothering maintainers to update to the next day or week's commit hash, and it uses our time when we already have things to do to maintain Void.

Also note: Flask is a utility for Python. It is system level. flaskbb uses Flask to do things. That's why we package Flask: it has a variety of uses and knows exactly what it can or can not control within a system. (Flask gets installed to a few directories, and just sits there. it doesn't require other programs be installed and then try to change their configurations before being usable.) I've heard a recommendation to use Ansible Galaxy to set up things like flaskbb, just in case that's of interest to you.
