### ISSUE TITLE
Packages working fine on aarch64 - absent from repository

### ISSUE THREAD

**Issue by E100Beta** [voidlinux/void-packages#6003]
I found that out while configuring Xorg. `xinit` and `xf86-video-fbdev` weren't in the main repos. I compiled and installed them manually with `xbps-src`, and they worked fine. There are no `only_for_arches` in `template`s, they compile without problems (natively and while cross-compiling). I assume there are more packages like these. Is there a reason why these packages a are not in official repos?

**Comment by pullmoll** [comment]
In this case xf86-video-fbdev is a dependency of the meta package xorg-video-drivers. This package also contains drivers which are only for archs x86_64/i686. This is the reason why xorg-video-drivers did never finish to build for aarch64*.

Since also noone build xf86-video-fbdev manually on the aarch64* builders, it is missing from the repository.
