### ISSUE TITLE
Package Request: AMDGPU-PRO

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#6396]
So it looks like my graphic card AMD R7 M445 4GB (TOPAZ TX) is only really recognized/supported on AMDGPU-PRO. 

Randr recognizes the GPU with amdgpu but DRI_PRIME does not work. It will always load the intel card on hybrid GPU. 

On AMD website it says that the pro version does support the M445 variant.

**Comment by Anachron** [comment]
Maybe I'm just stupid though? 

I was trying to use PRIME but no changes. Maybe someone can lead me to the right way.

**Comment by Anachron** [comment]
We can close this its already working by default I just didnt know glxinfo will always show intel.

**Comment by E100Beta** [comment]
PRIME never worked for me (R5 M230) with neither amdgpu nor radeon since I bought my laptop :( Never once used my dGPU. Which is okay since my iGPU is basically as powerful ¯\_(ツ)_/¯
There are some problems with porting AMDGPU-PRO to Void:
* There are binary components in it, so there is almost no hope for it to run on musl (which is somewhat okay, a lot of packages currently don't run on musl).
* AMDGPU-PRO currently only supports Xorg 1.18, whereas Void has 1.19 for quite some time already. AFAIK, maintainers decided against staying on earlier Xorg because of AMD Catalyst (see https://github.com/voidlinux/void-packages/issues/4159), so unless driver catches up, it won't work on Void.
EDIT: Oh, okay, glad you solved your problem 👍

**Comment by Anachron** [comment]
Thanks for you answer, I really appreciate it!

Sometimes you are searching hours for something that works because you trust a single program output to show the correct result...
