### ISSUE TITLE
Package Request: chkrootkit

### ISSUE THREAD

**Issue by ZweiSpeedruns** [voidlinux/void-packages#6460]
http://www.chkrootkit.org/

Utility to check locally for signs of a rootkit

**Comment by cr6git** [comment]
It's not easy... seems like chkrootkit needs to be patched, see this [discussion](https://forum.voidlinux.eu/t/chkrootkit-template/2610)...

**Comment by ZweiSpeedruns** [comment]
Huh, that's interesting. Looking at the discussion and doing my own research, the error would probably be fixed by adding `#include <fcntl.h>` to the file with the main function. `#include <sys/types.h>` and 
`#include <sys/stat.h>` may also be good for portability. I think these should be patched in at the `__linux__` ifdef in chklastlog.c

**Comment by zqqw** [comment]
There is more than one way to fix a problem, but I think the underlying trouble is in the headers wherever it is failing to build - MUSL, 64 bit GLIBC? It builds on 32 bit GLIBC so it is getting the correct defines from somewhere.
e.g. from /usr/share/include/unistd.h:
/* NOTE: These declarations also appear in <fcntl.h>; be sure to keep both
   files consistent.  Some systems have them there and some here, and some
   software depends on the macros being defined without including both.  */
So it would make more sense (to me) to patch the headers that are missing something so all software builds, not patch this particular code and then have to repeat the exercise.

**Comment by cr6git** [comment]
@zqqw It's really sweet of you to try to help us :wink:

**Comment by zqqw** [comment]
Well it's better than shouting answers at a quiz show on TV. I do try, how much I succeed is something else!
I emailed the bug about the hidden file scan failing on BTRFS to the maintainer, who is going to look into it by the way. I wouldn't know what to do about that except ask the BTRFS devs.
Perhaps the need to port things to MUSL is a security feature so MUSL shouldn't be 'fixed'.
It is getting fcntl.h on my system through sys/file.h, I couldn't check on that before as the forum was down and I couldn't remember your exact error message. Including fcntl.h would thus only explicitly add what is already implicitly added so wouldn't matter for GLIBC users.

**Comment by avoidr** [comment]
I just looked at the code. Weirdly, I get a different error than you. But the code has more problems than that. It would have to be "updated" a little bit. Some things changed since '97. Looking at it, I wouldn't run it as root.

It's simply missing headers, and using weird ifdefs. Like checking __linux__ for standard library headers… makes no sense.

And what is this?
```
#if __FreeBSD__ > 9
int main () { return 0; }
#else
```
Was this a joke, back in the day, or something?

My error was this:
```
chkwtmp.c:62:18: error: storage size of 'dummy' isn't known
  struct timezone dummy;
                  ^~~~~
chkwtmp.c:62:18: warning: unused variable 'dummy' [-Wunused-variable]
```
That finesse, look at that.

>If you include superfluous headers then you get a bigger binary

No, you don't, because
1. the linker doesn't include every function in the headers, but only those that are used
2. in most cases, the program is linked dynamically, so the library code is only referred to in the linked binary, and the actual code is in the *.so.

I would say this program is not even worth it. It's from '97. Shit changed.

**Comment by avoidr** [comment]
Btw, the program seems to be BSD-licensed:
https://github.com/Magentron/chkrootkit/blob/master/COPYRIGHT

**Comment by zqqw** [comment]
My error was caused by it looking for hidden directories. This works on EXT4 but not on BTRFS. You would never find these without running this program or one that replicated it's behaviour, it does something quite special if you investigate.
Extra headers do make a bigger binary, try compiling a c program with g++ instead of gcc! Perhaps this varies though, gcc can be configured in many ways at build time or in use. At this point in time you should probably use clang for smaller faster binaries.

**Comment by cr6git** [comment]
Take a look at the [build error](https://travis-ci.org/voidlinux/void-packages/jobs/296154024#L725) on x86_64-musl ...

**Comment by zqqw** [comment]
This is due to fcntl.h missing  as previously mentioned.
According to musl docs you should check individually for features as there is no __musl__ identifier. So at the end of the includes you could add something like this as a patch to follow the instructions from musl exactly:
```
chklastlog.c:

#ifndef O_RDONLY
#include <fcntl.h>
#endif
```
But you might as well add fcntl.h anywhere because it is still getting included indirectly with glibc from another header file, it is only that it isn't explicitly mentioned and musl doesnt include it from the musl headers that are explicitly included which is causing the error.

**Comment by maxice8** [comment]
Added on https://github.com/voidlinux/void-packages/commit/d9fe2cc97cb89abdc95ef84905e2d1edf1615b9e

**Comment by cr6git** [comment]
Yes I did the job, this issue can be CLOSED now.

**Comment by avoidr** [comment]
This can be closed, then.

**Comment by cr6git** [comment]
WHY THIS ISSUE IS STILL OPEN ??

**Comment by chneukirchen** [comment]
No need to scream.

The answer is: because the maintainers have more important things to do, apparently.

**Comment by cr6git** [comment]
sorry.
