### ISSUE TITLE
go: builds godoc and cover but doesn't package them

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#6931]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/go/template#L91-L97

Not sure when this broke or if it ever worked, but they don't end up in the package now. `godoc` is shipped with the official binariy package, `cover` isn't anymore.

**Comment by ebfe** [comment]
Since nobody complained and Debian and Arch also don't seem to ship either `godoc` or `cover` i'd suggest to drop them from the template.

**Comment by CMB** [comment]
For some reason, I needed godoc a while ago.  I built it manually, assuming
that there must have been a very good reason that it wasn't included
in the go package.

$ which godoc
/home/chris/.local/lib64/go/bin/godoc

**Comment by KenjiTakahashi** [comment]
FYI: On Arch, there's a separate `go-tools` package, which contains `godoc` and `cover`, among some other Go utils. AFAIR it was split at some point, so that users who just want to compile some Go code, do not need to download the whole tooling. I won't be surprised if there was a similar thing for Debian based distros.
