### ISSUE TITLE
Package Request: mozc

### ISSUE THREAD

**Issue by Altai-man** [voidlinux/void-packages#7343]
https://github.com/google/mozc - mozc is a widely used utility that works great in pair with ibus-anthy(already in the ecosystem) and makes Japanese input painless for everyone who need it.

**Comment by cr6git** [comment]
I think you will need [zinnia](https://taku910.github.io/zinnia/), which is not yet present in Void repository.

**Comment by Altai-man** [comment]
Well, certainly. Do not sure if it needs to be a separate issue though.

**Comment by mvf** [comment]
I have ported the mozc AUR PKGBUILD and will try to get it into shape for a PR over the next few days. If all you need is IBus, handwriting and Emacs integration, you can start using it [right now](/mvf/void-packages/tree/mozc). So far it's only been built and tested on x86_64 glibc though.

**Comment by mvf** [comment]
PR: #7507

**Comment by Altai-man** [comment]
Thanks a lot for your efforts!

**Comment by Altai-man** [comment]
@mvf, just tried your template. Thanks for all your efforts!

I've built mozc and mozc-ibus, then
```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
```
in `.xprofile`, reboot, `ibus-setup` - mozc is present. Set it as input method.

The ibus tray icon is here and I am able to choose mozc input too, input mode is hiragana, but the characters are not converted: not in browser, not in terminal.

However, with `emacs-mozc` package I can input Japanese properly in emacs.

Maybe you have any clues about what may be wrong? Nonetheless, emacs input works and it is thousand times better than nothing, so thank you very much.

**Comment by mvf** [comment]
You're very welcome. In fact, thank **you** very much for making me package this! Anthy (AFAIK the only Japanese IM in Void) is so horrible that I was using Google Docs with the Chrome input tools for everything. :sweat_smile:

What you are seeing is a known bug (#3168). On a fresh Void installation you have to run these two commands and log back in again:
```
sudo gtk-query-immodules-2.0 --update-cache
sudo gtk-query-immodules-3.0 --update-cache
```
This only needs to be done once. I have a proper fix sitting around, but didn't get around to a PR yet. Testing the change is a bit of a pain since one has to uninstall GTK.

As a side note, since you mention Hiragana input mode and `.xprofile`: Putting an `export IBUS_MOZC_DEFAULT_HIRAGANA=` in there should activate it by default.
