### ISSUE TITLE
dmenu-4.7 doesn't allow cyrillic input

### ISSUE THREAD

**Issue by gravicappa** [voidlinux/void-packages#7614]
It works when built from vanilla sources though.

**Comment by Duncaen** [comment]
Its built from "vanilla" sources, maybe a font issue?

**Comment by gravicappa** [comment]
It shows cyrillics correctly but inputting whose with keyboard yields nothing.

**Comment by liwakura** [comment]
This doesn't seem to be specific to cyrillic, it seems to be UTF-8 in general that cant be entered.
Also, UTF-8 characters enter something invisible into the searchbar (causes the search results to change), and those "invisible" characters can be deleted like normal characters.

This sounds like a font issue, but if you do "echo ä|dmenu" you cant select this entry by typing "ä" - which means that dmenu considers those two different characters.

Also, characters after an "invisible" one are likewise not visible, even if they are from the ascii range.

Judging from that, its probably a wrong input charset issue, and its not displayed because its not valid utf8.
