### ISSUE TITLE
GNOME metapackage broken

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#8010]
The Metapackage for the GNOME desktop is broken due to the move to version 3.26.
It depends in newer versions of gnome-calculator and gnome-calendar than there are in the repo.

It is looking for gnome-calculator>=3.25.92 and gnome-calendar>=3.26.0 .
The versions available in the repo are: gnome-calculator=3.24.0 and gnome-calendar=3.24.3.

**Comment by freedomrun** [comment]
$ sudo xbps-install -Su
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
MISSING: gnome-calculator>=3.25.92
MISSING: gnome-calendar>=3.26.0
MISSING: gnome-multi-writer>=3.26.0
MISSING: nautilus-sendto>=3.8.6
Transaction aborted due to unresolved dependencies.

**Comment by Sir-Boops** [comment]
Are you guys still having the issue?

**Comment by freedomrun** [comment]
Yes, there are still holdups:

MISSING: gnome-multi-writer>=3.26.0
MISSING: nautilus-sendto>=3.8.6
Transaction aborted due to unresolved dependencies.

**Comment by greywolf01** [comment]
For me it is Wirkung fine now.
Did a fresh install this morning and I'm now running GNOME 3.26.
The metapackage die work withkut a Problem.

TBH I don't know why it would ask for multi-writer and sendto as a dependency.
At least it didn't do that in my end.

**Comment by greywolf01** [comment]
For me it is Wirkung fine now.
Did a fresh install this morning and I'm now running GNOME 3.26.
The metapackage die work withkut a Problem.

TBH I don't know why it would ask for multi-writer and sendto as a dependency.
At least it didn't do that in my end.

**Comment by circhioz** [comment]
`gnome-apps` depends on `nautilus-sento` and `gnome-multi-writer`.
I tried to build multi-writer, but it requires an unreleased version of `polkit` (it hasn't got a revbump in 2 years...)

**Comment by circhioz** [comment]
Unresolved dependencies have been removed in f1f0a21db165f7a9dfbd59d1fe33264d5cfff154.
`gnome-apps` should be fine now. Any other issue?

**Comment by maxice8** [comment]
Well we merged a lot of stuff and i installed fine here locally, i'll assume it's resolved.

@the-maldridge

**Comment by maxice8** [comment]
let's try it again

@lemmi
