### ISSUE TITLE
libreoffice-5.4.0.3_3: broken, unresolvable shlib `libpoppler.so.70'

### ISSUE THREAD

**Issue by KozakIvan** [voidlinux/void-packages#8125]
Transaction aborted due to unresolved shlibs.

**Comment by alexey-nemovff** [comment]
Same issue reported by a friend of mine while trying to update hence failing to update. Runing Void i686.
`~$ sudo xbps-install -Su`
`[*] Updating 'https://repo.voidlinux.eu/current/i686-repodata' ...`
`inkscape-0.92.2_2: broken, unresolvable shlib 'libpoppler.so.70'`
`libreoffice-5.4.0.3_3: broken, unresolvable shlib 'libpoppler.so.70'`
`poppler-glib-0.59.0_1: broken, unresolvable shlib 'libpoppler.so.70'`
`Transaction aborted due to unresolved shlibs.`

**Comment by pullmoll** [comment]
The problem is that libreoffice currently fails to build for i686 due to a test failure.
Someone (read: me) has to identify and disable the failing test, or (which is improbable) fix the underlying issue.

**Comment by pullmoll** [comment]
It's worse than I had thought: libreoffice builds also crash when running unit tests for the database functions. I currently see no way how to fix this on our end. If you must use i686, you probably need to switch to a binary package and install it in e.g. /opt/libreofffice. I don't know if and when we can revive libreoffice for i686, sorry.

**Comment by cr6git** [comment]
@pullmoll You're not alone! ;) This night, I managed to build `libreoffice-5.4.2.2` on my Void i686 system. 
It took me ~9H, this is huge! See the end of my [build log](https://hastebin.com/kasedodoho.erl). 

This is pure i686 build environment, not cross compilation. 
Is my test relevant ? 
I have time today, do you want me to do another test for cross compilation x86_64 -> i686 ?

**Comment by pullmoll** [comment]
I did not try to cross build for i686 from x86_64, but used an i686 build environment. And there some unit tests for database functions segfaulted.

If your build succeeded on a real 32 bit hardware it suggests that our i686 build environment is not perfect. The problem is that we can't do much about it. I doubt we have true 32 bit hardware for the i686 builder to run on.

**Comment by cr6git** [comment]
I used come tricks found on the Arch [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libreoffice-fresh#n152) : 

````
	# don't run broken tests
	sed -i "/CppunitTest_sw_ooxmlexport9/d" sw/Module_sw.mk
````

````
	# many tests are broken when crossbuilding i686
	   make build-nocheck
````

Also, in `makedepends` I added `clucene-devel` that was missing.

**Comment by pullmoll** [comment]
@cr6git ok, so you disabled the crashing or failing tests. We could do that as well.
The problem with clucene-devel is that for *-musl it lacks a header file that is available in glibc builds, so we could add it only for i686 if building it from source is a problem.

**Comment by KeepBotting** [comment]
LibreOffice crashing on i686 is not new. Try the tricks detailed [here](https://forum.voidlinux.eu/t/solved-libreoffice-crashes-silently-on-startup/3393/22), you might find that your build works fine and the problem lies elsewhere.

**Comment by cr6git** [comment]
@KeepBotting Incredible! Booting using GRUB CMDLINE `stack_guard_gap=1` fixes the issue!!

**Comment by pullmoll** [comment]
I guess we could just make java a build time option in libreoffice which defaults to OFF.

**Comment by pullmoll** [comment]
@cr6git Thank you! I'm already working on it.
Currently compiling the pre-requisites and testing, if I can get i686 build done.
I'll disable java for all but x86_64.
